CREATE TABLE IF NOT EXISTS tbl_currency (
cur_code VARCHAR(3),
cur_display_type INT,
cur_id INT,
cur_name VARCHAR(42),
cur_symbol VARCHAR(6)
);
INSERT INTO tbl_currency VALUES
('USD',0,1,'United States Dollar','$'),
('GBP',0,2,'Pound','£'),
('EUR',0,3,'Euro','€'),
('VND',1,4,'Việt Nam Đồng','₫'),
('CNY',0,5,'Yuan Renminbi','¥'),
('JPY',0,6,'Yen','¥'),
('BRL',0,7,'Reais','R$'),
('RUB',0,8,'Rubles','₽'),
('KRW',0,9,'Won','₩'),
('THB',0,10,'Baht','฿'),
('INR',0,11,'India Rupee','₹'),
('CHF',0,12,'Francs','Fr.'),
('DKK',0,13,'Kroner','Kr'),
('SEK',0,14,'Sweden Krona','kr'),
('PLN',0,15,'Poland Zlotych','zł'),
('HUF',0,16,'Hungary Forint','Ft'),
('NOK',0,17,'Norwegian krone','kr'),
('BYR',0,18,'Belarusian ruble','Br'),
('DZD',0,19,'Algerian Dinar','DZD'),
('AUD',0,20,'Australia Dollars','AU$'),
('AZN',0,21,'Azerbaijan New Manats','ман'),
('ARS',0,22,'Argentina Pesos','$'),
('BDT',0,23,'Bangladeshi taka','BDT'),
('BOB',0,24,'Bolivianos','$b'),
('BGN',0,25,'Bulgarian lev','лв'),
('CAD',0,26,'Canada Dollars','C$'),
('CRC',0,27,'Colon','₡'),
('HRK',0,28,'Croatian kuna','kn'),
('CLP',0,29,'Chile Pesos','$'),
('COP',0,30,'Colombia Pesos','COL$'),
('CZK',1,31,'Česká koruna','Kč'),
('MNT',0,32,'Tugriks','₮'),
('HNL',0,33,'Lempiras','L'),
('MAD',0,34,'Moroccan Dirham','MAD'),
('MXN',0,35,'Mexico Pesos','Mex$'),
('NGN',0,36,'Nairas','₦'),
('NZD',0,37,'New Zealand Dollars','NZ$'),
('HKD',0,38,'Hong Kong Dollars','HK$'),
('LAK',0,39,'Lao kip','₭'),
('KES',0,40,'Kenya Shilling','KSh'),
('DOP',0,41,'Dominican Republic Pesos','RD$'),
('GHS',0,42,'Ghana Cedi','GH₵'),
('ILS',0,43,'Israel New Shekels','₪'),
('IDR',0,44,'Indonesia Rupiah','Rp'),
('IRR',0,45,'Iranian Rial','IRR'),
('JOD',0,46,'Jordanian dinar','JOD'),
('KGS',0,47,'Kyrgyzstan Som','сом'),
('LVL',0,48,'Latvia Lati','Ls'),
('LTL',0,49,'Lithuania Litai','Lt'),
('MKD',0,50,'Macedonia Denars','ден'),
('MZN',0,51,'Mozambique Meticais','MT'),
('MYR',0,52,'Malaysia Ringgits','RM'),
('ANG',0,53,'Netherlands Antilles Guilders','NAƒ'),
('TWD',0,54,'New Taiwan Dollar','NT$'),
('NIO',0,55,'Nicaragua Cordobas','C$'),
('NPR',0,56,'Nepalese Rupee','NRs'),
('OMR',0,57,'Oman Rials','﷼'),
('PAB',0,58,'Panama Balboa','B/.'),
('PHP',0,59,'Philippines Pesos','₱'),
('PYG',0,60,'Paraguay Guarani','Gs'),
('PEN',0,61,'Peru Nuevos Soles','S/.'),
('QAR',0,62,'Qatar riyal','QR'),
('RON',0,63,'Romanian Leu','lei'),
('TTD',0,64,'Trinidad and Tobago Dollars','TT$'),
('TRY',0,65,'Turkish Liras','TL.'),
('TND',0,66,'Tunisian dinar','DT'),
('UAH',0,67,'Ukraine Hryvnia','₴'),
('UYU',0,68,'Uruguay Pesos','$U'),
('AED',0,69,'United Arab Emirates dirham','AED'),
('VEF',0,70,'Venezuela Bolivares Fuertes','Bs'),
('KZT',0,71,'Kazakhstani tenge','₸'),
('RSD',0,72,'Serbia Dinar','din.'),
('SAR',0,73,'Saudi Arabian Riyal','SR'),
('SKK',0,74,'Slovak crown','SKK'),
('ZAR',0,75,'South African rand','R'),
('SGD',0,76,'Singapore Dollars','S$'),
('LKR',0,77,'Sri Lanka rupee','Rs'),
('ZMW',0,78,'Zambian kwacha','ZK'),
('LBP',0,79,'Lebanese Pound','LBP'),
('KWD',0,80,'Kuwaiti Dinar','K.D'),
('AFN',0,81,'Afghan afghani','AFN'),
('ALL',0,82,'Albanian lek','ALL'),
('AOA',0,83,'Angolan kwanza','AOA'),
('XCD',0,84,'East Caribbean dollar','EC$'),
('AMD',0,85,'Armenian dram','AMD'),
('AWG',0,86,'Aruban florin','ƒ'),
('BSD',0,87,'Bahamian dollar','B$'),
('BHD',0,88,'Bahraini dinar','BHD'),
('BBD',0,89,'Barbadian dollar','Bds'),
('BZD',0,90,'Belize dollar','BZ$'),
('CFA',0,91,'West African CFA franc','XOF'),
('BMD',0,92,'Bermudian dollar','BD$'),
('BTN',0,93,'Bhutanese ngultrum','Nu.'),
('BAM',0,94,'Bosnia and Herzegovina konvertibilna marka','KM'),
('BWP',0,95,'Botswana pula','P'),
('BND',0,96,'Brunei dollar','B$'),
('BIF',0,97,'Burundi franc','FBu'),
('KHR',0,98,'Khmer riel','KHR'),
('CVE',0,99,'Cape Verdean escudo','Esc'),
('KYD',0,100,'Cayman Islands dollar','KY$'),
('KMF',0,101,'Comorian franc','KMF'),
('CDF',0,102,'Congolese franc','F'),
('CUC',0,103,'Cuban peso','₱'),
('DJF',0,104,'Djiboutian franc','Fdj'),
('EGP',0,105,'Egyptian pound','£'),
('GQE',0,106,'Central African CFA franc','CFA'),
('ERN',0,107,'Eritrean nakfa','Nfa'),
('EEK',0,108,'Estonian kroon','KR'),
('ETB',0,109,'Ethiopian birr','Br'),
('FKP',0,110,'Falkland Islands pound','£'),
('FJD',0,111,'Fijian dollar','FJ$'),
('XPF',0,112,'CFP franc','F'),
('XAF',0,113,'Central African CFA franc','CFA'),
('GMD',0,114,'Gambian dalasi','D'),
('GEL',0,115,'Georgian lari','GEL'),
('GIP',0,116,'Gibraltar pound','£'),
('GTQ',0,117,'Guatemalan quetzal','Q'),
('GNF',0,118,'Guinean franc','FG'),
('GYD',0,119,'Guyanese dollar','GY$'),
('HTG',0,120,'Haitian gourde','G'),
('ISK',0,121,'Icelandic króna','kr'),
('XDR',0,122,'Special Drawing Rights','SDR'),
('IQD',0,123,'Iraqi dinar','IQD'),
('JMD',0,124,'Jamaican dollar','J$'),
('KPW',0,125,'Korean won','W'),
('LSL',0,126,'Lesotho loti','M'),
('LRD',0,127,'Liberian dollar','L$'),
('LYD',0,128,'Libyan dinar','LD'),
('MOP',0,129,'Macanese pataca','MOP$'),
('MGA',0,130,'Malagasy ariary','Ar'),
('MWK',0,131,'Malawian kwacha','MK'),
('MVR',0,132,'Maldivian rufiyaa','Rf'),
('MRO',0,133,'Mauritanian ouguiya','UM'),
('MUR',0,134,'Mauritian rupee','Rs'),
('MDL',0,135,'Moldovan leu','MDL'),
('MNT',0,136,'Mongolian tugrik','₮'),
('MZM',0,137,'Mozambican metical','MTn'),
('MMK',0,138,'Myanma kyat','K'),
('PKR',0,139,'Pakistani rupee','Rs.'),
('PGK',0,140,'Papua New Guinean kina','K'),
('RWF',0,141,'Rwandan franc','RF'),
('STD',0,142,'São Tomé and Príncipe dobra','Db'),
('SCR',0,143,'Seychellois rupee','SR'),
('SLL',0,144,'Sierra Leonean leone','Le'),
('SBD',0,145,'Solomon Islands dollar','SI$'),
('SOS',0,146,'Somali shilling','Sh.'),
('SHP',0,147,'Saint Helena pound','£'),
('SDG',0,148,'Sudanese pound','SDG'),
('SRD',0,149,'Surinamese dollar','$'),
('SZL',0,150,'Swazi lilangeni','E'),
('SYP',0,151,'Syrian pound','SYP'),
('TJS',0,152,'Tajikistani somoni','TJS'),
('TZS',0,153,'Tanzanian shilling','TZS'),
('TMT',0,154,'Turkmen manat','m'),
('UGX',0,155,'Ugandan shilling','USh'),
('UZS',0,156,'Uzbekistani som','UZS'),
('VUV',0,157,'Vanuatu vatu','VT'),
('VEB',0,158,'Venezuelan bolivar','Bs'),
('WST',0,159,'Samoan tala','WS$'),
('YER',0,160,'Yemeni rial','YER'),
('ZWD',0,161,'Zimbabwean dollar','Z$'),
('BTC',0,162,'Bitcoin','฿'),
('LTC',0,163,'Litecoin','Ł'),
('BYN',0,164,'New Belarusian ruble','BR');